### PR TITLE
UI Styling

### PR DESCRIPTION
**Pull request by shinyichen**
Make the style consistent with ADS
localhost_5050_link_gateway_2012ApJS 199 26H_DATA

0 0 0 0_5050_link_gateway_2014AJ 147 124M

### CODE REVIEW

**Review by golnazads — APPROVED** [review]
Looks great Jennifer.

**Comment by golnazads** [comment]
Hi Jennifer. Looks great. I approved it, so at any time you like you can
merge it, feel free. However, please wait on making a release. Nemanja
just told me that there is an issue and we want to fix it before your
release. thank you so much.
golnaz

**Comment by shinyichen** [comment]
@golnazads @marblestation 
Just made an update to remove the static folder and use image resources from ADS root. And inlined CSS. So the ADS static resources is not modified.

This means the images won't display in localhost. Will have to see them in deployment.

**Comment by marblestation** [comment]
@shinyichen Awesome! Thanks! If @golnazads is happy with this, it looks ready to be merged then!

**Comment by golnazads** [comment]
@Sergio Blanco Cuaresma ***@***.***> @shinyichen
<https://github.com/shinyichen> yes, all set. I think you can make a
release as well if you would like.

**Pull request merged**
